# Generated by Django 5.1.4 on 2025-01-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(default='Default Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mobile_num',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
    ]
